WAKE_WORDS: dict[str, set[str]] = {
    "ko": {
        "스피키",
        "스피기",
        "스피키야",
        "speaki",
        "speaky",
        "spiky",
        "su pi ki",
        "좋아요",
        "조아요",
        "조아 요",
        "좋아 요",
        "joayo",
        "jo ayo",
        "choayo",
        "chuayo",
        "cuayo",
    },
    "en": {
        "speaki",
        "speaky",
        "spiky",
        "pumpkin",
        "pumpkins",
        "supiki",
        "su pi ki",
    },
    "ja": {
        "スピーキー",
        "スピーキ",
        "スピキ",
        "speaki",
        "speaky",
        "su pi ki",
    },
}

GRAMMAR_WAKE_WORDS: dict[str, set[str]] = {
    "ko": {
        "스피키",
        "스피기",
        "스피키야",
        "좋아요",
        "조아요",
        "조아 요",
        "좋아 요",
    },
    "en": {
        "speaki",
        "speaky",
        "spiky",
        "supiki",
        "pumpkin",
        "pumpkins",
    },
    "ja": {
        "スピーキー",
        "スピーキ",
        "スピキ",
    },
}

DELAYED_WAKE_WORDS: set[str] = {
    "speaki",
    "speaky",
    "spiky",
    "supiki",
    "su pi ki",
    "스피키",
    "스피기",
    "스피키야",
    "スピーキー",
    "スピーキ",
    "スピキ",
}
