WAKE_WORDS: dict[str, set[str]] = {
    "ko": {
        "스피키",
        "스피기",
        "스피키야",
        "네르",
        "네루",
        "speaki",
        "speaky",
        "ner",
        "neru",
        "spiky",
        "su pi ki",
        "좋아요",
        "조아요",
        "조아 요",
        "좋아 요",
        "좋아",
        "조아",
        "joayo",
        "jo ayo",
        "choayo",
        "chuayo",
        "cuayo",
    },
    "en": {
        "speaki",
        "speaky",
        "ner",
        "neru",
        "spiky",
        "pumpkin",
        "pumpkins",
        "supiki",
        "su pi ki",
    },
    "ja": {
        "スピーキー",
        "スピーキ",
        "スピキ",
        "ネル",
        "寧琉",
        "speaki",
        "speaky",
        "ner",
        "neru",
        "su pi ki",
    },
}

DELAYED_WAKE_WORDS: set[str] = {
    "speaki",
    "speaky",
    "spiky",
    "supiki",
    "su pi ki",
    "스피키",
    "스피기",
    "스피키야",
    "スピーキー",
    "スピーキ",
    "スピキ",
}
